# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c34dce05458bcd7d48476db5adb57d3bddb3588091609439dc076cabf233e301d7ee5de3a39b3d4ceadf20711119d6111b88ccb476acc8f472156fd68f1d4c5e

test:
  secret_key_base: cb7089e9d4d51b9f84592ce40a311223338b7d135e2de61d54db30b47414981ab4abfcfcb046f80b93e7b0566f3a1daf55b4e0f8a999bfd7aaf2fcb3dfb1105e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
